const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname
	];
};
self.C3_JsPropNameTable = [
	{giris: 0},
	{basla_btn: 0},
	{Mouse: 0},
	{on_sayfa: 0},
	{Audio: 0},
	{oyun_background: 0},
	{tablolar: 0},
	{ilk_x: 0},
	{ilk_y: 0},
	{DragDrop: 0},
	{sayilar_btn: 0},
	{yonerge: 0},
	{tablo_alti_sayilar: 0},
	{Array: 0},
	{Touch: 0},
	{Sine: 0},
	{kirmizi: 0},
	{bilgi_btn: 0},
	{tebrikler: 0},
	{yenidenoyna_btn: 0},
	{anasayfa_btn: 0},
	{tam_ekran_btn: 0},
	{ses_ac: 0},
	{Browser: 0},
	{bilgi: 0},
	{buton_family: 0},
	{DogruSayisi: 0},
	{Ses_Kapali: 0},
	{Efekt_Ses_DB: 0},
	{OlayAvcilariCalindi: 0}
];

self.InstanceType = {
	giris: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	on_sayfa: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	oyun_background: class extends self.ISpriteInstance {},
	tablolar: class extends self.ISpriteInstance {},
	sayilar_btn: class extends self.ISpriteInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tablo_alti_sayilar: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	kirmizi: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	yenidenoyna_btn: class extends self.ISpriteInstance {},
	anasayfa_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	ses_ac: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bilgi: class extends self.ISpriteInstance {},
	buton_family: class extends self.ISpriteInstance {}
}