const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetX,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{kontrol_et_btn: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{yonerge: 0},
	{tebrikler: 0},
	{Audio: 0},
	{Touch: 0},
	{c_zemin: 0},
	{cark: 0},
	{Tween: 0},
	{cark_ucgen: 0},
	{Pin: 0},
	{SariNokta_Carpisma: 0},
	{UyariMetni: 0},
	{oyun2_zemin: 0},
	{kitap: 0},
	{sorular: 0},
	{sepet: 0},
	{IlkX: 0},
	{IlkY: 0},
	{DragDrop: 0},
	{armut: 0},
	{SonucMetniSol: 0},
	{CevapHakki: 0},
	{MesajKutusu: 0},
	{SonucMetniSag: 0},
	{GuncelA: 0},
	{yonerge1: 0},
	{tekrar_denemelisin: 0},
	{daha_dikkatli_olmalisin: 0},
	{"9patch": 0},
	{son_hak: 0},
	{KalpNo: 0},
	{kalp: 0},
	{kalp_efekt: 0},
	{Fam_butonlar: 0},
	{Fam_cark: 0},
	{DonmeHizi: 0},
	{Surukleniyor: 0},
	{BaslangicAcisi: 0},
	{TiklamaFarki: 0},
	{EskiAci: 0},
	{GelenDilim: 0},
	{GuncelAci: 0},
	{CevrildiMi: 0},
	{KalanHak: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0},
	{DogruCevap: 0},
	{SepettekiArmut: 0},
	{EkranKilitli: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	kontrol_et_btn: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	c_zemin: class extends self.ISpriteInstance {},
	cark: class extends self.ISpriteInstance {},
	cark_ucgen: class extends self.ISpriteInstance {},
	SariNokta_Carpisma: class extends self.ISpriteInstance {},
	UyariMetni: class extends self.ITextInstance {},
	oyun2_zemin: class extends self.ISpriteInstance {},
	kitap: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	sepet: class extends self.ISpriteInstance {},
	armut: class extends self.ISpriteInstance {},
	SonucMetniSol: class extends self.ITextInstance {},
	CevapHakki: class extends self.ITextInstance {},
	MesajKutusu: class extends self.ITextInstance {},
	SonucMetniSag: class extends self.ITextInstance {},
	GuncelA: class extends self.ITextInstance {},
	yonerge1: class extends self.ISpriteInstance {},
	tekrar_denemelisin: class extends self.ISpriteInstance {},
	daha_dikkatli_olmalisin: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	son_hak: class extends self.ISpriteInstance {},
	kalp: class extends self.ISpriteInstance {},
	kalp_efekt: class extends self.ISpriteInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {},
	Fam_cark: class extends self.ISpriteInstance {}
}