const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{yonerge: 0},
	{tebrikler: 0},
	{Audio: 0},
	{Touch: 0},
	{CozulduMu: 0},
	{Tween: 0},
	{SoruSekil: 0},
	{CevapSekil: 0},
	{OkCizgisi: 0},
	{DoluMu: 0},
	{SoruNoktasi: 0},
	{CevapNoktasi: 0},
	{BagliCizgiUID: 0},
	{OkUcu: 0},
	{ParlamaEfekti: 0},
	{AsamaMetni: 0},
	{ZamanMetni: 0},
	{OyunSonuMetni: 0},
	{Fam_butonlar: 0},
	{Asama: 0},
	{EslenenCift: 0},
	{SecilenSoruUID: 0},
	{CizimAktif: 0},
	{AktifOkUID: 0},
	{GecenSure: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	SoruSekil: class extends self.ISpriteInstance {},
	CevapSekil: class extends self.ISpriteInstance {},
	OkCizgisi: class extends self.ISpriteInstance {},
	SoruNoktasi: class extends self.ISpriteInstance {},
	CevapNoktasi: class extends self.ISpriteInstance {},
	OkUcu: class extends self.ISpriteInstance {},
	ParlamaEfekti: class extends self.IParticlesInstance {},
	AsamaMetni: class extends self.ITextInstance {},
	ZamanMetni: class extends self.ITextInstance {},
	OyunSonuMetni: class extends self.ITextInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {}
}