const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{spr_Eskiz: 0},
	{ID: 0},
	{spr_Parca_acikyesil: 0},
	{spr_Parca_Kahve: 0},
	{spr_Parca_Mor: 0},
	{spr_Parca_Pembe: 0},
	{spr_Parca_sari: 0},
	{spr_Parca_Turuncu: 0},
	{spr_Parca_yesil: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{JSON_LevelData: 0},
	{AJAX: 0},
	{yonerge: 0},
	{LevelDizisi: 0},
	{tebrikler: 0},
	{Audio: 0},
	{txt_Sayac: 0},
	{Touch: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Fam_Parcalar: 0},
	{Fam_butonlar: 0},
	{EditMode: 0},
	{LevelName: 0},
	{YerlesenParca: 0},
	{LevelIndex: 0},
	{ToplamLevel: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	spr_Eskiz: class extends self.ISpriteInstance {},
	spr_Parca_acikyesil: class extends self.ISpriteInstance {},
	spr_Parca_Kahve: class extends self.ISpriteInstance {},
	spr_Parca_Mor: class extends self.ISpriteInstance {},
	spr_Parca_Pembe: class extends self.ISpriteInstance {},
	spr_Parca_sari: class extends self.ISpriteInstance {},
	spr_Parca_Turuncu: class extends self.ISpriteInstance {},
	spr_Parca_yesil: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	JSON_LevelData: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	LevelDizisi: class extends self.IArrayInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	txt_Sayac: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Fam_Parcalar: class extends self.ISpriteInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {}
}