const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{anasayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{tam_ekran_btn: 0},
	{ses_ac: 0},
	{ana_sayfa: 0},
	{background: 0},
	{Mouse: 0},
	{Touch: 0},
	{bilgi: 0},
	{sorular: 0},
	{SiralamaNo: 0},
	{secenekler: 0},
	{tebrikler: 0},
	{sonuc_gostergesi: 0},
	{ID: 0},
	{Tween: 0},
	{oda_objeleri: 0},
	{Audio: 0},
	{Browser: 0},
	{butonlar: 0},
	{tiklama_kilit: 0},
	{HedefX: 0},
	{HedefY: 0},
	{Ses_Kapali: 0},
	{Efekt_Ses_DB: 0}
];

self.InstanceType = {
	anasayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	ses_ac: class extends self.ISpriteInstance {},
	ana_sayfa: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	bilgi: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	secenekler: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	sonuc_gostergesi: class extends self.ISpriteInstance {},
	oda_objeleri: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	butonlar: class extends self.ISpriteInstance {}
}