const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetPaused
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{yonerge: 0},
	{tebrikler: 0},
	{Audio: 0},
	{tik: 0},
	{kisa_kirmizi: 0},
	{uzun_kirmizi: 0},
	{d_harfi: 0},
	{u_harfi1: 0},
	{r_harfi: 0},
	{u_harfi2: 0},
	{s_harfi: 0},
	{t_harfi: 0},
	{DogruSecenek: 0},
	{TiklandiMi: 0},
	{TiklamaAlani: 0},
	{Touch: 0},
	{Sprite: 0},
	{MesajKutusu: 0},
	{GeriSayimMetni: 0},
	{oyun: 0},
	{ara_layer: 0},
	{Fam_butonlar: 0},
	{caldi: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0},
	{DogruSayisi2: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	tik: class extends self.ISpriteInstance {},
	kisa_kirmizi: class extends self.ISpriteInstance {},
	uzun_kirmizi: class extends self.ISpriteInstance {},
	d_harfi: class extends self.ISpriteInstance {},
	u_harfi1: class extends self.ISpriteInstance {},
	r_harfi: class extends self.ISpriteInstance {},
	u_harfi2: class extends self.ISpriteInstance {},
	s_harfi: class extends self.ISpriteInstance {},
	t_harfi: class extends self.ISpriteInstance {},
	TiklamaAlani: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MesajKutusu: class extends self.ISpriteInstance {},
	GeriSayimMetni: class extends self.ITextInstance {},
	oyun: class extends self.ISpriteInstance {},
	ara_layer: class extends self.ISpriteInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {}
}