const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{anaysayfa_btn: 0},
	{basla_btn: 0},
	{bilgi_btn: 0},
	{ses_ac_btn: 0},
	{tam_ekran_btn: 0},
	{yeniden_oyna_btn: 0},
	{giris: 0},
	{bilgi: 0},
	{Mouse: 0},
	{arka_plan: 0},
	{Keyboard: 0},
	{Browser: 0},
	{yonerge: 0},
	{tebrikler: 0},
	{Audio: 0},
	{slot: 0},
	{MatchID: 0},
	{t1: 0},
	{t2: 0},
	{t3: 0},
	{t4: 0},
	{t5: 0},
	{t6: 0},
	{t7: 0},
	{t8: 0},
	{BaslangicX: 0},
	{BaslangicY: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{KarisikDizi: 0},
	{Touch: 0},
	{Fam_butonlar: 0},
	{Sine: 0},
	{Tamamlanmislar: 0},
	{DragDrop: 0},
	{Parcalar: 0},
	{SuruklenenID: 0},
	{SuruklenenUID: 0},
	{DropX: 0},
	{DropY: 0},
	{EslestiMi: 0},
	{HedefX: 0},
	{HedefY: 0},
	{MuzikSesi: 0},
	{AnlikSes: 0},
	{Ses_Kapali: 0},
	{LayoutMuzikSesi: 0}
];

self.InstanceType = {
	anaysayfa_btn: class extends self.ISpriteInstance {},
	basla_btn: class extends self.ISpriteInstance {},
	bilgi_btn: class extends self.ISpriteInstance {},
	ses_ac_btn: class extends self.ISpriteInstance {},
	tam_ekran_btn: class extends self.ISpriteInstance {},
	yeniden_oyna_btn: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	arka_plan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	yonerge: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	slot: class extends self.ISpriteInstance {},
	t1: class extends self.ISpriteInstance {},
	t2: class extends self.ISpriteInstance {},
	t3: class extends self.ISpriteInstance {},
	t4: class extends self.ISpriteInstance {},
	t5: class extends self.ISpriteInstance {},
	t6: class extends self.ISpriteInstance {},
	t7: class extends self.ISpriteInstance {},
	t8: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	KarisikDizi: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Fam_butonlar: class extends self.ISpriteInstance {},
	Tamamlanmislar: class extends self.ISpriteInstance {},
	Parcalar: class extends self.ISpriteInstance {}
}